apiVersion: v1
kind: Service
metadata:
  name: argo-server-patch
spec:
  type: NodePort
  ports:
    - name: web
      port: 2746
      targetPort: 2746
      # Mapped to host port 2746 by the k3d loadbalancer (see k3d.conf).
      nodePort: 30746
